//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 11:17:16 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://getusroi.com/internalevents/Dispatcher")
package com.getusroi.eventframework.jaxb;
